# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a5009890c8cf5f7785e273a0f0f586298ce28ae13542a9d8e26ded18d74d0916bb92b0e609d19eb734c204364e87aa6a2f31d4e18c8bf6aa53f7509f910614e

# Use different runs of `rake secret` for development and test
test:
  secret_key_base: 1e608a8a77a9ef862c3f02f3909517ad49fd4a9136158fa1ed0593ae224ea8ae702c84af33d275983ea2ee4309cecc8f0421dd0800b4824b1125902e22cf1547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
